"""added tags column

Revision ID: 03eb5917cd2b
Revises: 54bc57244d5e
Create Date: 2025-04-14 15:05:10.494192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03eb5917cd2b'
down_revision: Union[str, None] = '54bc57244d5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('margin_platform_seller_id_company_category_product_name_fkey', 'margin', type_='foreignkey')
    op.create_foreign_key('fk_margin_product', 'margin', 'product', ['platform', 'seller_id', 'company', 'product_name', 'category'], ['platform', 'seller_id', 'company', 'product_name', 'category'])
    op.add_column('product', sa.Column('tags', sa.TEXT(), nullable=True))
    op.alter_column('product', 'category',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('product', 'company',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('product', 'product_name',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'product_name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('product', 'company',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('product', 'category',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('product', 'tags')
    op.drop_constraint('fk_margin_product', 'margin', type_='foreignkey')
    op.create_foreign_key('margin_platform_seller_id_company_category_product_name_fkey', 'margin', 'product', ['platform', 'seller_id', 'company', 'category', 'product_name'], ['platform', 'seller_id', 'company', 'category', 'product_name'])
    # ### end Alembic commands ###
