"""added_category_on_product

Revision ID: 54bc57244d5e
Revises: 30e699fe3b88
Create Date: 2025-04-10 14:24:59.444394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54bc57244d5e'
down_revision: Union[str, None] = '30e699fe3b88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('category', sa.TEXT(), nullable=False))
    op.execute("ALTER TABLE product DROP CONSTRAINT uq_product CASCADE")
    op.create_unique_constraint('uq_product', 'product', ['platform', 'seller_id', 'company', 'category', 'product_name'])
    op.execute("COMMIT")  # 새로 생성된 unique 제약 조건 반영을 위해 커밋 수행
    op.create_foreign_key(None, 'margin', 'product', ['platform', 'seller_id', 'company', 'category', 'product_name'], ['platform', 'seller_id', 'company', 'category', 'product_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_product', 'product', type_='unique')
    op.create_unique_constraint('uq_product', 'product', ['platform', 'seller_id', 'company', 'product_name'])
    op.drop_column('product', 'category')
    op.drop_constraint(None, 'margin', type_='foreignkey')
    op.create_foreign_key('margin_platform_seller_id_company_product_name_fkey', 'margin', 'product', ['platform', 'seller_id', 'company', 'product_name'], ['platform', 'seller_id', 'company', 'product_name'])
    # ### end Alembic commands ###
