"""Fix product_id int to bigint

Revision ID: 64d978a73cf1
Revises: 77e7c05a4349
Create Date: 2025-04-17 17:10:09.096123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64d978a73cf1'
down_revision: Union[str, None] = '77e7c05a4349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE product DROP CONSTRAINT IF EXISTS uq_product_platform_seller_company_product_category;")
    op.execute("ALTER TABLE product ADD CONSTRAINT uq_product_platform_seller_company_product_category UNIQUE (platform, seller_id, company, product_name, category, tags);")
    op.add_column('margin', sa.Column('tags', sa.TEXT(), nullable=True))
    op.create_foreign_key('fk_margin_product', 'margin', 'product', ['platform', 'seller_id', 'company', 'product_name', 'category', 'tags'], ['platform', 'seller_id', 'company', 'product_name', 'category', 'tags'])
    op.add_column('ob_history', sa.Column('company', sa.TEXT(), nullable=False))
    op.drop_column('ob_history', 'compnay')
    op.alter_column('product', 'product_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'product_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.add_column('ob_history', sa.Column('compnay', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('ob_history', 'company')
    op.drop_constraint('fk_margin_product', 'margin', type_='foreignkey')
    op.execute("ALTER TABLE product DROP CONSTRAINT IF EXISTS uq_product_platform_seller_company_product_category;")
    # ### end Alembic commands ###
